version: '3.8'

services:
  yt-burmese-hardsub-worker:
    build: .
    image: hellergodric/yt-burmese-hardsub-worker:latest
    runtime: nvidia
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - RUNPOD_SECRET_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - RUNPOD_SECRET_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - RUNPOD_SECRET_S3_BUCKET=${AWS_S3_BUCKET_NAME}
      - RUNPOD_SECRET_S3_ENDPOINT_URL=${AWS_ENDPOINT_URL}
    volumes:
      - ./logs:/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
